name: pypyr-in-tox
author: pypyr
description: Run any pypyr task-runner automation pipeline inside your own tox environment.
inputs:
  pipeline: 
    description: Pipeline name and input args.
    required: true
  python-version:
    description: Version of Python
    required: false
    default: 'x'
runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
      shell: bash
    - name: Install base dependencies.
      run: |
        python -m pip install --upgrade pip
        pip install tox
      shell: bash
    - name: Run ${{ pipeline }} pipeline inside tox. Set tox.ini in your repo root to manage environment dependencies.
      run: tox ${{ pipeline }}
      shell: bash